server:
  #端口号
  port: 8080
spring:
  application:
    #应用名字
    name: dijia_take_out

  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.150.129:3306/waimai_db?characterEncoding=utf-8
        username: root
        password: 123456
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.150.130:3306/waimai_db?characterEncoding=utf-8
        username: root
        password: root
    masterslave:
      # 读写分离配置   load-balance负载均衡   round_robin 轮询
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
    #开启允许bean定义覆盖
  main:
    allow-bean-definition-overriding: true

  #Redis配置
  redis:
    host: 192.168.150.129
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据过期时间，可以不写

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    #（如将shopping_cat转化为ShoppingCat,user_id转化为UserId）
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #主键生成方式
      id-type: ASSIGN_ID

dijia:
  path: D:\dijia-images\

