server:
  #端口号
  port: 8080
spring:
  application:
    #应用名字
    name: dijia_take_out
  datasource:
    druid:
      #mysql配置
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/waimai_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456

  #Redis配置
  redis:
    host: 192.168.150.129
    port: 6379
    database: 0

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    #（如将shopping_cat转化为ShoppingCat,user_id转化为UserId）
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #主键生成方式
      id-type: ASSIGN_ID

dijia:
  path: D:\dijia-images\

